### ISSUE TITLE
app_shots

### ISSUE THREAD

**Issue by smnshuvo** [cpcincubator/class-organizer-and-day-scheduler#5]
![Screenshot_1592490149](https://user-images.githubusercontent.com/26756885/85032968-388ffc00-b1a2-11ea-9503-25788b639618.png)

![Screenshot_1592490155](https://user-images.githubusercontent.com/26756885/85033043-4d6c8f80-b1a2-11ea-9187-33fc1ca365c9.png)

![Screenshot_1592490171](https://user-images.githubusercontent.com/26756885/85033105-61b08c80-b1a2-11ea-871b-8abb7d5193ad.png)
![Screenshot_1592490185](https://user-images.githubusercontent.com/26756885/85033243-8f95d100-b1a2-11ea-8ee0-68603ade78ce.png)
)
![Screenshot_1592490754](https://user-images.githubusercontent.com/26756885/85033678-092dbf00-b1a3-11ea-9010-eba40ebb1b7e.png)

**Comment by shahmedme** [comment]
great. almost ready?

**Comment by smnshuvo** [comment]
Yeah. Ready to launch.
