### ISSUE TITLE
Create new form is covered with keyboard

### ISSUE THREAD

**Issue by shahmedme** [cpcincubator/class-organizer-and-day-scheduler#7]
When someone is going to create schedule for new course (at the time of typing course name, code, etc) keyboard covered the full area of input field that's why it's not visible what user is typing. May be because the form isn't scrollable or something. It would be better if someone fix this.

![1](https://user-images.githubusercontent.com/24731446/85190112-db499700-b2d6-11ea-9a29-2521e76dfe84.jpg)

**Comment by smnshuvo** [comment]
Yeah. The form is not semi scroll-able, test devices' screen size was long, this is why it wasn't making issue.
I'd be glad if anyone:
- [ ] Put `+@id/input_routine_day_of_the_week` and every fellow component inside the `Scrollview`

**Comment by smnshuvo** [comment]
Waiting for your responses..
@AshrafulAlamS @musfiqur55

**Comment by smnshuvo** [comment]
Got no response. Fixed by self. 
![Screenshot_1592835347](https://user-images.githubusercontent.com/26756885/85298128-84ee7b00-b4c5-11ea-91b8-951da6482d13.png)

**Comment by neelniloy** [comment]
Debug APK

https://drive.google.com/file/d/13lIP6KsktNVI-VKoTatbzKTViVta5OYL/view?usp=sharing
