### ISSUE TITLE
Class time font is too large

### ISSUE THREAD

**Issue by shahmedme** [cpcincubator/class-organizer-and-day-scheduler#8]
Text about class starting time is almost overflowed the area of it's parent. There should have equal padding on all side. Also if the font is smaller, it would be great.

![Screenshot_1](https://user-images.githubusercontent.com/24731446/85190240-231cee00-b2d8-11ea-9eae-7c03d7e8e480.png)

**Comment by smnshuvo** [comment]
I'll check that out.

**Comment by smnshuvo** [comment]
Check this file [item_routine.xml](https://github.com/cpcincubator/class-organizer-and-day-scheduler/blob/master/app/src/main/res/layout/item_routine.xml)
The `@+id/item_routine_starting_time` text size is set to 24dp, try to change it to 24sp or  accordingly, and run in a low resolution device.
It should take less time than me writing this comment.

**Comment by smnshuvo** [comment]
Got no response from the assignee, fixed by self 
![issue8](https://user-images.githubusercontent.com/26756885/85297587-bd418980-b4c4-11ea-9f96-1ac709218b02.png)
